# Generated by Django 2.2 on 2021-05-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetails', '0004_enrollment_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='studentid',
        ),
    ]
