# Generated by Django 2.2 on 2021-05-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('code', models.IntegerField()),
                ('department', models.CharField(max_length=500)),
                ('instructor', models.CharField(max_length=500)),
            ],
        ),
    ]
