# Generated by Django 2.2 on 2021-05-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='id',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='course_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
