# Generated by Django 2.2 on 2021-05-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdetails_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='course',
            field=models.ManyToManyField(db_table='Courseenrollment', to='coursedetails.Coursedetails'),
        ),
    ]
